export const stories = [
  {
    profileImg: "/stories/profile-1.png",
    profileName: "Product",
    title: ["Building SaaS", "platforms that", "creators love"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-1.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "AI",
    title: ["Autonomous agents", "for smarter", "business automation"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-2.jpg",
  },
  {
    profileImg: "/stories/profile-3.png",
    profileName: "Branding",
    title: ["Identity systems", "built for the", "creator economy"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-3.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Web3",
    title: ["On-chain products", "for digital brands", "and communities"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-4.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Automation",
    title: ["Workflows that", "eliminate friction", "and scale fast"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-5.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Emerging Tech",
    title: ["Experimenting at", "the edge of what", "technology can do"],
    linkLabel: "Explore Work",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-6.jpg",
  },
];
